# Generated by Django 5.2.2 on 2025-06-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoUser',
        ),
    ]
