# Generated by Django 5.2.2 on 2025-06-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='stock',
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
