# Generated by Django 5.2.2 on 2025-06-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_carritouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
