# Generated by Django 5.2.2 on 2025-06-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
