# Generated by Django 5.2.2 on 2025-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1 - Muy mala'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Muy buena')], default=5),
        ),
    ]
