# Generated by Django 5.2.2 on 2025-06-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendalibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
